from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from futebol.views import (
    ai_agent_create,
    ai_agent_edit,
    ai_agent_list,
    ai_center,
    ai_provider_create,
    ai_provider_edit,
    ai_provider_list,
    approval_flow_list,
    approval_request_create,
    approval_request_list,
    approve_request,
    audit_log_list,
    automation_center,
    bi_center,
    cancel_request,
    club_create,
    club_edit,
    club_list,
    competition_create,
    competition_edit,
    competition_list,
    contract_create,
    contract_edit,
    contract_list,
    evidence_create,
    evidence_list,
    external_system_create,
    external_system_edit,
    external_system_list,
    home,
    integration_export,
    integration_hub,
    integration_import,
    integration_record_create,
    integration_record_list,
    integration_record_mark_processed,
    integration_record_retry,
    knowledge_source_create,
    knowledge_source_edit,
    knowledge_source_list,
    knowledge_source_import_url,
    landing,
    mark_notification_read,
    match_create,
    match_edit,
    match_list,
    negotiation_create,
    negotiation_edit,
    negotiation_list,
    notification_create,
    notification_list,
    onboarding,
    proposal_create,
    proposal_edit,
    proposal_list,
    prediction_center,
    public_api_docs,
    public_api_matches,
    public_api_overview,
    reject_request,
    report_center,
    root_dispatch,
    tenant_admin,
    tenant_membership_edit,
    tenant_user_create,
    tenant_user_edit,
    transfer_center,
)

urlpatterns = [
    path('', root_dispatch, name='root'),
    path('institucional/', landing, name='landing'),
    path('onboarding/', onboarding, name='onboarding'),
    path('painel/', home, name='home'),
    path('tenant/admin/', tenant_admin, name='tenant-admin'),
    path('tenant/usuarios/novo/', tenant_user_create, name='tenant-user-create'),
    path('tenant/usuarios/<int:pk>/editar/', tenant_user_edit, name='tenant-user-edit'),
    path('tenant/vinculos/<int:pk>/editar/', tenant_membership_edit, name='tenant-membership-edit'),
    path('clubes/', club_list, name='club-list'),
    path('clubes/novo/', club_create, name='club-create'),
    path('clubes/<int:pk>/editar/', club_edit, name='club-edit'),
    path('competicoes/', competition_list, name='competition-list'),
    path('competicoes/nova/', competition_create, name='competition-create'),
    path('competicoes/<int:pk>/editar/', competition_edit, name='competition-edit'),
    path('partidas/', match_list, name='match-list'),
    path('partidas/nova/', match_create, name='match-create'),
    path('partidas/<int:pk>/editar/', match_edit, name='match-edit'),
    path('aprovacoes/', approval_flow_list, name='approval-flow-list'),
    path('solicitacoes-aprovacao/', approval_request_list, name='approval-request-list'),
    path('solicitacoes-aprovacao/nova/', approval_request_create, name='approval-request-create'),
    path('auditoria/', audit_log_list, name='audit-log-list'),
    path('solicitacoes-aprovacao/<int:pk>/aprovar/', approve_request, name='approval-request-approve'),
    path('solicitacoes-aprovacao/<int:pk>/rejeitar/', reject_request, name='approval-request-reject'),
    path('solicitacoes-aprovacao/<int:pk>/cancelar/', cancel_request, name='approval-request-cancel'),
    path('notificacoes/', notification_list, name='notification-list'),
    path('notificacoes/nova/', notification_create, name='notification-create'),
    path('notificacoes/<int:pk>/marcar-lida/', mark_notification_read, name='notification-mark-read'),
    path('transferencias/', transfer_center, name='transfer-center'),
    path('relatorios/', report_center, name='report-center'),
    path('relatorios/bi/', bi_center, name='bi-center'),
    path('previsoes/', prediction_center, name='prediction-center'),
    path('api/publica/', public_api_docs, name='public-api-docs'),
    path('api/publica/<slug:tenant_slug>/visao-geral/', public_api_overview, name='public-api-overview'),
    path('api/publica/<slug:tenant_slug>/partidas/', public_api_matches, name='public-api-matches'),
    path('transferencias/contratos/', contract_list, name='contract-list'),
    path('transferencias/contratos/novo/', contract_create, name='contract-create'),
    path('transferencias/contratos/<int:pk>/editar/', contract_edit, name='contract-edit'),
    path('transferencias/negociacoes/', negotiation_list, name='negotiation-list'),
    path('transferencias/negociacoes/nova/', negotiation_create, name='negotiation-create'),
    path('transferencias/negociacoes/<int:pk>/editar/', negotiation_edit, name='negotiation-edit'),
    path('transferencias/propostas/', proposal_list, name='proposal-list'),
    path('transferencias/propostas/nova/', proposal_create, name='proposal-create'),
    path('transferencias/propostas/<int:pk>/editar/', proposal_edit, name='proposal-edit'),
    path('transferencias/evidencias/', evidence_list, name='evidence-list'),
    path('transferencias/evidencias/nova/', evidence_create, name='evidence-create'),
    path('integracoes/', integration_hub, name='integration-hub'),
    path('integracoes/sistemas/', external_system_list, name='external-system-list'),
    path('integracoes/sistemas/novo/', external_system_create, name='external-system-create'),
    path('integracoes/sistemas/<int:pk>/editar/', external_system_edit, name='external-system-edit'),
    path('integracoes/registros/', integration_record_list, name='integration-record-list'),
    path('integracoes/registros/novo/', integration_record_create, name='integration-record-create'),
    path('integracoes/registros/<int:pk>/processar/', integration_record_mark_processed, name='integration-record-mark-processed'),
    path('integracoes/registros/<int:pk>/reprocessar/', integration_record_retry, name='integration-record-retry'),
    path('integracoes/importar/', integration_import, name='integration-import'),
    path('integracoes/exportar/', integration_export, name='integration-export'),
    path('automacoes/', automation_center, name='automation-center'),
    path('ia/', ai_center, name='ai-center'),
    path('ia/providers/', ai_provider_list, name='ai-provider-list'),
    path('ia/providers/novo/', ai_provider_create, name='ai-provider-create'),
    path('ia/providers/<int:pk>/editar/', ai_provider_edit, name='ai-provider-edit'),
    path('ia/fontes/', knowledge_source_list, name='knowledge-source-list'),
    path('ia/fontes/importar-url/', knowledge_source_import_url, name='knowledge-source-import-url'),
    path('ia/fontes/nova/', knowledge_source_create, name='knowledge-source-create'),
    path('ia/fontes/<int:pk>/editar/', knowledge_source_edit, name='knowledge-source-edit'),
    path('ia/agentes/', ai_agent_list, name='ai-agent-list'),
    path('ia/agentes/novo/', ai_agent_create, name='ai-agent-create'),
    path('ia/agentes/<int:pk>/editar/', ai_agent_edit, name='ai-agent-edit'),
    path('ia/scouting/', ai_center, name='scouting-center'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]
