# Generated by Django 4.2.30 on 2026-07-08 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('futebol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('target_model', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160)),
                ('registration_code', models.CharField(blank=True, default='', max_length=64)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160)),
                ('scope', models.CharField(choices=[('league', 'Liga'), ('cup', 'Copa'), ('championship', 'Campeonato'), ('tournament', 'Torneio')], default='championship', max_length=24)),
                ('active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=160)),
                ('name', models.CharField(max_length=160)),
                ('season_year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('open', 'Aberta'), ('locked', 'Bloqueada'), ('running', 'Em andamento'), ('finished', 'Encerrada'), ('archived', 'Arquivada')], default='draft', max_length=16)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='futebol.competition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['-season_year', 'competition__name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=160)),
                ('order', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendada'), ('active', 'Ativa'), ('closed', 'Encerrada')], default='draft', max_length=16)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='futebol.competitionedition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['edition__competition__name', 'edition__season_year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExternalSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('payment', 'Pagamento'), ('email', 'E-mail'), ('storage', 'Armazenamento'), ('import', 'Importação'), ('export', 'Exportação'), ('other', 'Outro')], default='other', max_length=16)),
                ('base_url', models.URLField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(max_length=64)),
                ('scheduled_at', models.DateTimeField()),
                ('venue', models.CharField(blank=True, default='', max_length=160)),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('confirmed', 'Confirmada'), ('played', 'Disputada'), ('cancelled', 'Cancelada'), ('postponed', 'Adiada')], default='scheduled', max_length=16)),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('immutable_after', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('away_club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='futebol.club')),
                ('home_club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='futebol.club')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='futebol.competitionphase')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('accepted', 'Aceita'), ('rejected', 'Rejeitada'), ('withdrawn', 'Cancelada')], default='open', max_length=16)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='futebol.club')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('age_min', models.PositiveSmallIntegerField(default=0)),
                ('age_max', models.PositiveSmallIntegerField(default=99)),
                ('active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='futebol.club')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['club__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviada'), ('accepted', 'Aceita'), ('rejected', 'Rejeitada')], default='draft', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='futebol.club')),
                ('negotiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='futebol.negotiation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160)),
                ('document_id', models.CharField(blank=True, default='', max_length=32)),
                ('kind', models.CharField(choices=[('athlete', 'Atleta'), ('coach', 'Técnico'), ('staff', 'Comissão'), ('referee', 'Arbitragem'), ('other', 'Outro')], default='athlete', max_length=16)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp')], default='in_app', max_length=16)),
                ('subject', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Na fila'), ('sent', 'Enviada'), ('failed', 'Falhou'), ('read', 'Lida')], default='queued', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='negotiation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='futebol.person'),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant'),
        ),
        migrations.CreateModel(
            name='MatchLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, default='', max_length=32)),
                ('is_starter', models.BooleanField(default=True)),
                ('captain', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineups', to='futebol.club')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='futebol.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineups', to='futebol.person')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['match__scheduled_at', 'club__name', 'player__full_name'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('goal', 'Gol'), ('yellow_card', 'Cartão amarelo'), ('red_card', 'Cartão vermelho'), ('substitution', 'Substituição'), ('foul', 'Falta'), ('other', 'Outro')], max_length=24)),
                ('minute', models.PositiveSmallIntegerField()),
                ('period', models.CharField(blank=True, default='', max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='futebol.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='futebol.person')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['minute', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correlation_id', models.CharField(max_length=120)),
                ('external_object_id', models.CharField(blank=True, default='', max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='received', max_length=32)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('external_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_records', to='futebol.externalsystem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('suspended', 'Suspenso'), ('terminated', 'Encerrado')], default='draft', max_length=16)),
                ('termination_reason', models.TextField(blank=True, default='')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='futebol.club')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='futebol.person')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['-start_date', 'person__full_name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_registration_notice_hours', models.PositiveSmallIntegerField(default=24)),
                ('red_card_suspension_matches', models.PositiveSmallIntegerField(default=1)),
                ('publish_quorum_percent', models.PositiveSmallIntegerField(default=60)),
                ('immutability_window_hours', models.PositiveSmallIntegerField(default=24)),
                ('import_export_max_mb', models.PositiveSmallIntegerField(default=10)),
                ('import_export_max_rows', models.PositiveIntegerField(default=5000)),
                ('conflict_policy', models.CharField(choices=[('skip', 'Pular'), ('overwrite', 'Sobrescrever'), ('error', 'Erro')], default='skip', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ruleset', to='futebol.competition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['competition__name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('create', 'Criar'), ('update', 'Atualizar'), ('delete', 'Excluir'), ('approve', 'Aprovar'), ('reject', 'Rejeitar'), ('import', 'Importar'), ('export', 'Exportar')], max_length=16)),
                ('object_id', models.CharField(max_length=64)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=80)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('cancelled', 'Cancelada')], default='pending', max_length=16)),
                ('target_model', models.CharField(max_length=120)),
                ('target_object_id', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='futebol.approvalflow')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='teamcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'club', 'name'), name='uniq_category_per_club'),
        ),
        migrations.AddConstraint(
            model_name='teamcategory',
            constraint=models.CheckConstraint(check=models.Q(('age_min__lte', models.F('age_max'))), name='category_age_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('tenant', 'full_name'), name='uniq_person_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='matchlineup',
            constraint=models.UniqueConstraint(fields=('tenant', 'match', 'player'), name='uniq_lineup_player_per_match'),
        ),
        migrations.AddConstraint(
            model_name='matchevent',
            constraint=models.CheckConstraint(check=models.Q(('minute__gte', 0)), name='match_event_minute_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('tenant', 'reference_code'), name='uniq_match_ref_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('tenant', 'phase', 'scheduled_at', 'home_club', 'away_club'), name='uniq_match_slot_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(check=models.Q(('home_club', models.F('away_club')), _negated=True), name='match_home_away_distinct'),
        ),
        migrations.AddConstraint(
            model_name='integrationrecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'external_system', 'correlation_id'), name='uniq_integration_correlation_per_system'),
        ),
        migrations.AddConstraint(
            model_name='externalsystem',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_external_system_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('tenant', 'person', 'club'), name='uniq_active_contract_per_pair'),
        ),
        migrations.AddConstraint(
            model_name='competitionphase',
            constraint=models.UniqueConstraint(fields=('tenant', 'edition', 'code'), name='uniq_phase_code_per_edition'),
        ),
        migrations.AddConstraint(
            model_name='competitionphase',
            constraint=models.UniqueConstraint(fields=('tenant', 'edition', 'order'), name='uniq_phase_order_per_edition'),
        ),
        migrations.AddConstraint(
            model_name='competitionedition',
            constraint=models.UniqueConstraint(fields=('tenant', 'competition', 'slug'), name='uniq_edition_slug_per_competition'),
        ),
        migrations.AddConstraint(
            model_name='competitionedition',
            constraint=models.UniqueConstraint(fields=('tenant', 'competition', 'season_year'), name='uniq_edition_season_per_competition'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_competition_slug_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_competition_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_club_slug_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_club_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='approvalflow',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_approval_flow_code_per_tenant'),
        ),
    ]
