# Generated by Django 4.2.30 on 2026-07-08 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('futebol', '0005_approvalrequest_resolution_and_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome', models.CharField(choices=[('approved', 'Aprovada'), ('rejected', 'Rejeitada')], max_length=16)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Decisão de aprovação',
                'verbose_name_plural': 'Decisões de aprovação',
                'ordering': ['decided_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalFlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('required_role', models.CharField(choices=[('admin_tenant', 'Administrador do tenant'), ('gestor_clube', 'Gestor do clube'), ('gestor_competicao', 'Gestor da competição'), ('aprovador', 'Aprovador'), ('delegado_partida', 'Delegado da partida'), ('auditor_somente_leitura', 'Auditor somente leitura'), ('admin_plataforma', 'Administrador da plataforma')], max_length=32)),
                ('requires_evidence', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Etapa de aprovação',
                'verbose_name_plural': 'Etapas de aprovação',
                'ordering': ['flow__name', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.CharField(max_length=64)),
                ('file', models.FileField(blank=True, upload_to='evidencias/')),
                ('url', models.URLField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Evidência',
                'verbose_name_plural': 'Evidências',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Solicitação de aprovação', 'verbose_name_plural': 'Solicitações de aprovação'},
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='target_kind',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('negociacao', 'Negociação'), ('partida', 'Partida'), ('escalacao', 'Escalação'), ('inscricao', 'Inscrição'), ('transferencia', 'Transferência')], max_length=24),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='futebol.approvalflow'),
        ),
        migrations.AddConstraint(
            model_name='approvalflow',
            constraint=models.UniqueConstraint(fields=('tenant', 'target_kind'), name='uniq_approval_flow_target_kind_per_tenant'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalflowstep',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='futebol.approvalflow'),
        ),
        migrations.AddField(
            model_name='approvalflowstep',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='decided_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='futebol.approvalrequest'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='futebol.approvalflowstep'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant'),
        ),
        migrations.AddConstraint(
            model_name='approvalflowstep',
            constraint=models.UniqueConstraint(fields=('tenant', 'flow', 'order'), name='uniq_flow_step_order_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='approvaldecision',
            constraint=models.UniqueConstraint(fields=('request', 'step'), name='uniq_decision_per_step_per_request'),
        ),
    ]
