# Generated by Django 4.2.30 on 2026-07-08 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0006_approvaldecision_approvalflowstep_evidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160)),
                ('purpose', models.CharField(blank=True, default='', max_length=180)),
                ('system_prompt', models.TextField()),
                ('model_override', models.CharField(blank=True, default='', max_length=120)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.2, max_digits=3)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=240)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('document', 'Documento'), ('report', 'Relatório'), ('reference', 'Referência'), ('manual', 'Manual'), ('url', 'URL'), ('other', 'Outro')], default='other', max_length=16)),
                ('source_path', models.CharField(blank=True, default='', max_length=300)),
                ('source_url', models.URLField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('openrouter', 'OpenRouter'), ('ollama', 'Ollama'), ('gemini', 'Google Gemini'), ('custom', 'Custom')], default='custom', max_length=32)),
                ('model_name', models.CharField(max_length=120)),
                ('api_base_url', models.URLField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIAgentSourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='futebol.aiagent')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_links', to='futebol.knowledgesource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='aiagent',
            name='knowledge_sources',
            field=models.ManyToManyField(blank=True, related_name='agents', through='futebol.AIAgentSourceLink', to='futebol.knowledgesource'),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='futebol.aiprovider'),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.UniqueConstraint(fields=('tenant', 'identifier'), name='uniq_knowledge_source_identifier_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='aiprovider',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_ai_provider_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='aiagentsourcelink',
            constraint=models.UniqueConstraint(fields=('tenant', 'agent', 'source'), name='uniq_ai_agent_source_link_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='aiagent',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_ai_agent_slug_per_tenant'),
        ),
    ]
