# Generated by Django 4.2.30 on 2026-07-08 23:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0007_aiagent_knowledgesource_aiprovider_aiagentsourcelink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='kind',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('openrouter', 'OpenRouter'), ('ollama', 'Ollama'), ('opencode', 'OpenCode Go'), ('gemini', 'Google Gemini'), ('custom', 'Custom')], default='custom', max_length=32),
        ),
        migrations.CreateModel(
            name='TenantModuleSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_code', models.CharField(max_length=40)),
                ('module_name', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('plan_name', models.CharField(blank=True, default='', max_length=120)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'verbose_name': 'Módulo contratado',
                'verbose_name_plural': 'Módulos contratados',
                'ordering': ['module_name'],
            },
        ),
        migrations.CreateModel(
            name='TenantBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#1d6fe8', max_length=9, validators=[django.core.validators.RegexValidator(message='Informe uma cor no formato hexadecimal, por exemplo #1d6fe8.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('secondary_color', models.CharField(default='#0c274a', max_length=9, validators=[django.core.validators.RegexValidator(message='Informe uma cor no formato hexadecimal, por exemplo #1d6fe8.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('background_color', models.CharField(default='#06162d', max_length=9, validators=[django.core.validators.RegexValidator(message='Informe uma cor no formato hexadecimal, por exemplo #1d6fe8.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('accent_color', models.CharField(default='#55a7ff', max_length=9, validators=[django.core.validators.RegexValidator(message='Informe uma cor no formato hexadecimal, por exemplo #1d6fe8.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('logo_url', models.URLField(blank=True, default='')),
                ('favicon_url', models.URLField(blank=True, default='')),
                ('symbol_url', models.URLField(blank=True, default='')),
                ('public_title', models.CharField(default='SaaS do Futebol', max_length=120)),
                ('public_subtitle', models.CharField(default='Operação multi-tenant', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='futebol.tenant')),
            ],
            options={
                'verbose_name': 'Identidade visual do tenant',
                'verbose_name_plural': 'Identidades visuais dos tenants',
            },
        ),
        migrations.AddConstraint(
            model_name='tenantmodulesubscription',
            constraint=models.UniqueConstraint(fields=('tenant', 'module_code'), name='uniq_module_subscription_per_tenant'),
        ),
    ]
