# Generated by Django 4.2.30 on 2026-07-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0008_alter_aiprovider_kind_tenantmodulesubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='public_api_key',
            field=models.CharField(blank=True, default='', help_text='Chave da API pública específica deste tenant. Vazio = API desabilitada.', max_length=64),
        ),
    ]
