# Generated by Django 4.2.30 on 2026-07-12 01:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('futebol', '0014_remove_tenant_public_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.CharField(choices=[('balanced', 'Equilibrado'), ('offensive', 'Ofensivo'), ('conservative', 'Conservador')], max_length=16)),
                ('formation', models.CharField(max_length=16)),
                ('summary', models.TextField()),
                ('attacking_plan', models.JSONField(default=list)),
                ('defensive_plan', models.JSONField(default=list)),
                ('transitions', models.JSONField(default=list)),
                ('set_pieces', models.JSONField(default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('confidence', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'ordering': ['variant'],
            },
        ),
        migrations.CreateModel(
            name='LineupDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('reviewed', 'Revisado'), ('archived', 'Arquivado')], default='draft', max_length=16)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineup_drafts', to='futebol.club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_lineup_drafts', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_drafts', to='futebol.match')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lineup_draft', to='futebol.gameplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('ready', 'Pronto para revisão'), ('failed', 'Falhou')], default='draft', max_length=16)),
                ('data_snapshot', models.JSONField(default=dict)),
                ('confidence', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('analyzed_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_dossiers', to='futebol.club')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_match_dossiers', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_dossiers', to='futebol.match')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialistOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.CharField(choices=[('tactical', 'Análise tática'), ('physical', 'Preparação física'), ('defense', 'Defesa'), ('attack', 'Ataque'), ('scout', 'Olheiro'), ('set_pieces', 'Bola parada'), ('environment', 'Ambiente e logística')], max_length=24)),
                ('summary', models.TextField()),
                ('recommendations', models.JSONField(default=list)),
                ('confidence', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('limitations', models.JSONField(blank=True, default=list)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='futebol.matchdossier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['specialty'],
            },
        ),
        migrations.CreateModel(
            name='LineupDraftPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=16)),
                ('tactical_role', models.CharField(blank=True, default='', max_length=80)),
                ('is_starter', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('rationale', models.TextField(blank=True, default='')),
                ('minute_limit', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(130)])),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='futebol.lineupdraft')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineup_draft_selections', to='futebol.person')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['-is_starter', 'order', 'player__full_name'],
            },
        ),
        migrations.CreateModel(
            name='GamePlanPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=16)),
                ('tactical_role', models.CharField(blank=True, default='', max_length=80)),
                ('is_starter', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('rationale', models.TextField(blank=True, default='')),
                ('minute_limit', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(130)])),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_plan_selections', to='futebol.club')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='futebol.gameplan')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_plan_selections', to='futebol.person')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['-is_starter', 'order', 'player__full_name'],
            },
        ),
        migrations.AddField(
            model_name='gameplan',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='futebol.matchdossier'),
        ),
        migrations.AddField(
            model_name='gameplan',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant'),
        ),
        migrations.CreateModel(
            name='AthleteSportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_position', models.CharField(max_length=16)),
                ('secondary_positions', models.JSONField(blank=True, default=list)),
                ('preferred_foot', models.CharField(choices=[('right', 'Direito'), ('left', 'Esquerdo'), ('both', 'Ambidestro'), ('unknown', 'Não informado')], default='unknown', max_length=16)),
                ('tactical_roles', models.JSONField(blank=True, default=list)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_profiles', to='futebol.person')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['player__full_name'],
            },
        ),
        migrations.CreateModel(
            name='AthleteMatchAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('limited', 'Disponível com limite'), ('doubt', 'Dúvida'), ('unavailable', 'Indisponível')], default='available', max_length=16)),
                ('max_minutes', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(130)])),
                ('readiness', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('note', models.TextField(blank=True, default='')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_availabilities', to='futebol.club')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_availabilities', to='futebol.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_availabilities', to='futebol.person')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['match__scheduled_at', 'player__full_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='specialistopinion',
            constraint=models.UniqueConstraint(fields=('tenant', 'dossier', 'specialty'), name='uniq_specialist_opinion_per_dossier'),
        ),
        migrations.AddConstraint(
            model_name='matchdossier',
            constraint=models.UniqueConstraint(fields=('tenant', 'match', 'analyzed_club', 'version'), name='uniq_match_dossier_version'),
        ),
        migrations.AddConstraint(
            model_name='lineupdraftplayer',
            constraint=models.UniqueConstraint(fields=('tenant', 'draft', 'player'), name='uniq_lineup_draft_player'),
        ),
        migrations.AddConstraint(
            model_name='gameplanplayer',
            constraint=models.UniqueConstraint(fields=('tenant', 'plan', 'player'), name='uniq_game_plan_player'),
        ),
        migrations.AddConstraint(
            model_name='gameplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'dossier', 'variant'), name='uniq_game_plan_variant_per_dossier'),
        ),
        migrations.AddConstraint(
            model_name='athletesportprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'player'), name='uniq_athlete_sport_profile_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='athletematchavailability',
            constraint=models.UniqueConstraint(fields=('tenant', 'match', 'player'), name='uniq_availability_per_match_player'),
        ),
    ]
