# Generated by Django 4.2.30 on 2026-07-12 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('futebol', '0015_gameplan_lineupdraft_matchdossier_specialistopinion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsDataImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset_id', models.CharField(max_length=120)),
                ('dataset_version', models.CharField(max_length=80)),
                ('content_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='processing', max_length=16)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('manifest', models.JSONField(default=dict)),
                ('license_id', models.CharField(max_length=80)),
                ('attribution', models.CharField(max_length=240)),
                ('quality', models.CharField(max_length=40)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sports_data_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SportsDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('local_dataset', 'Dataset local'), ('football_data_org', 'football-data.org'), ('club_internal', 'Dados internos do clube')], max_length=32)),
                ('capabilities', models.JSONField(default=list)),
                ('license_id', models.CharField(max_length=80)),
                ('license_url', models.URLField(blank=True, default='')),
                ('attribution', models.CharField(max_length=240)),
                ('quality', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SportsDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.CharField(max_length=64)),
                ('provider_record_id', models.CharField(max_length=160)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('source_url', models.URLField(blank=True, default='')),
                ('content_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='futebol.sportsdataimportbatch')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='futebol.sportsdatasource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['capability', 'provider_record_id'],
            },
        ),
        migrations.AddField(
            model_name='sportsdataimportbatch',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='futebol.sportsdatasource'),
        ),
        migrations.AddField(
            model_name='sportsdataimportbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant'),
        ),
        migrations.AddConstraint(
            model_name='sportsdatasource',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_sports_data_source_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='sportsdatarecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'source', 'capability', 'provider_record_id'), name='uniq_sports_data_provider_record'),
        ),
        migrations.AddConstraint(
            model_name='sportsdataimportbatch',
            constraint=models.UniqueConstraint(fields=('tenant', 'source', 'dataset_id', 'dataset_version', 'content_hash'), name='uniq_sports_data_import_content'),
        ),
    ]
