# Generated by Django 4.2.30 on 2026-07-12 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0016_sportsdataimportbatch_sportsdatasource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistopinion',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist_opinions', to='futebol.aiagent'),
        ),
        migrations.AddField(
            model_name='specialistopinion',
            name='execution_mode',
            field=models.CharField(default='deterministic', max_length=24),
        ),
        migrations.AddField(
            model_name='specialistopinion',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
