# Generated by Django 4.2.30 on 2026-07-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0018_gameplanplayer_pitch_x_gameplanplayer_pitch_y_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sportsdatarecord',
            name='uniq_sports_data_provider_record',
        ),
        migrations.AddConstraint(
            model_name='sportsdatarecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'batch', 'capability', 'provider_record_id'), name='uniq_sports_data_record_per_batch'),
        ),
    ]
