# Generated by Django 4.2.30 on 2026-07-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0019_preserve_sports_data_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistopinion',
            name='evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='specialistopinion',
            name='execution_mode',
            field=models.CharField(choices=[('deterministic', 'Determinístico'), ('provider', 'Provedor de IA'), ('fallback', 'Fallback determinístico')], default='deterministic', max_length=24),
        ),
    ]
