# Generated by Django 4.2.30 on 2026-07-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0020_specialistopinion_evidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistopinion',
            name='specialty',
            field=models.CharField(choices=[('coordinator', 'Coordenador técnico'), ('tactical', 'Análise tática'), ('physical', 'Preparação física'), ('defense', 'Defesa'), ('attack', 'Ataque'), ('scout', 'Olheiro'), ('set_pieces', 'Bola parada'), ('environment', 'Ambiente e logística')], max_length=24),
        ),
    ]
