# Generated by Django 4.2.30 on 2026-07-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0021_add_coordinator_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsdatarecord',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sportsdatasource',
            name='adapter_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sportsdatasource',
            name='last_error',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='sportsdatasource',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sportsdatasource',
            name='operational_status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('testing', 'Em teste'), ('active', 'Ativa'), ('degraded', 'Degradada'), ('disabled', 'Desabilitada'), ('revoked', 'Revogada'), ('research_only', 'Somente P&D'), ('contract_required', 'Contrato necessário')], default='draft', max_length=24),
        ),
        migrations.AddField(
            model_name='sportsdatasource',
            name='schema_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='sportsdatasource',
            name='kind',
            field=models.CharField(choices=[('local_dataset', 'Dataset local'), ('football_data_org', 'football-data.org'), ('club_internal', 'Dados internos do clube'), ('statsbomb_open', 'StatsBomb Open Data'), ('skillcorner_open', 'SkillCorner Open Data'), ('licensed_provider', 'Provider licenciado')], max_length=32),
        ),
    ]
