# Generated by Django 4.2.30 on 2026-07-12 20:30

from django.db import migrations, models
import django.db.models.deletion
import futebol.models


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0022_sportsdatarecord_raw_payload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsDataArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.CharField(max_length=64)),
                ('provider_object_id', models.CharField(max_length=160)),
                ('artifact_version', models.CharField(max_length=80)),
                ('schema_version', models.CharField(max_length=32)),
                ('format', models.CharField(default='jsonl', max_length=16)),
                ('compression', models.CharField(default='none', max_length=16)),
                ('file', models.FileField(upload_to=futebol.models.sports_data_artifact_path)),
                ('content_hash', models.CharField(max_length=64)),
                ('byte_size', models.PositiveBigIntegerField(default=0)),
                ('item_count', models.PositiveBigIntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('staged', 'Preparando'), ('ready', 'Pronto'), ('failed', 'Falhou')], default='staged', max_length=16)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='futebol.sportsdataimportbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sportsdataartifact',
            constraint=models.UniqueConstraint(fields=('tenant', 'batch', 'capability', 'provider_object_id', 'artifact_version'), name='uniq_sports_artifact_version'),
        ),
    ]
