# Generated by Django 4.2.30 on 2026-07-12 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('futebol', '0023_sportsdataartifact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacticalInsightReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_id', models.CharField(max_length=64)),
                ('decision', models.CharField(choices=[('approved_training', 'Aprovada para treinamento'), ('rejected', 'Rejeitada')], max_length=24)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactical_reviews', to='futebol.sportsdataartifact')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tactical_insight_reviews', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tacticalinsightreview',
            constraint=models.UniqueConstraint(fields=('tenant', 'artifact', 'evidence_id'), name='uniq_tactical_review_per_evidence'),
        ),
    ]
