# Generated by Django 4.2.30 on 2026-07-12 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('futebol', '0025_sportsdatasource_external_ai_processing_allowed_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tacticalagentopinion',
            name='uniq_tactical_agent_opinion',
        ),
        migrations.AddField(
            model_name='sportsdatasource',
            name='external_ai_authorization_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sportsdatasource',
            name='external_ai_authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sportsdatasource',
            name='external_ai_authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_sports_ai_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sportsdatasource',
            name='external_ai_provider_scope',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tacticalagentopinion',
            name='review_decision',
            field=models.CharField(blank=True, choices=[('approved_training', 'Aprovada para treinamento'), ('rejected', 'Rejeitada')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='tacticalagentopinion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tacticalagentopinion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_tactical_agent_opinions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='tacticalagentopinion',
            constraint=models.UniqueConstraint(condition=models.Q(('execution_mode', 'provider')), fields=('tenant', 'artifact', 'agent', 'prompt_hash'), name='uniq_provider_tactical_opinion'),
        ),
    ]
