# Generated by Django 4.2.30 on 2026-07-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0026_remove_tacticalagentopinion_uniq_tactical_agent_opinion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacticalagentopinion',
            name='evidence_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='tacticalagentopinion',
            name='limitations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='tacticalagentopinion',
            name='recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
