# Generated by Django 4.2.30 on 2026-07-12 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('futebol', '0027_alter_tacticalagentopinion_evidence_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacticalCommissionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Na fila'), ('running', 'Em execução'), ('partial', 'Concluída parcialmente'), ('completed', 'Concluída'), ('failed', 'Falhou'), ('cancelled', 'Cancelada')], default='queued', max_length=16)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('requested_specialties', models.JSONField(default=list)),
                ('max_provider_calls', models.PositiveSmallIntegerField(default=8)),
                ('provider_calls_used', models.PositiveSmallIntegerField(default=0)),
                ('synthesis', models.JSONField(blank=True, default=dict)),
                ('conflicts', models.JSONField(blank=True, default=list)),
                ('plan_variants', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=80)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_runs', to='futebol.sportsdataartifact')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_tactical_commission_runs', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_tactical_commission_runs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TacticalCommissionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.CharField(choices=[('coordinator', 'Coordenador técnico'), ('tactical', 'Análise tática'), ('physical', 'Preparação física'), ('defense', 'Defesa'), ('attack', 'Ataque'), ('scout', 'Olheiro'), ('set_pieces', 'Bola parada'), ('environment', 'Ambiente e logística')], max_length=24)),
                ('status', models.CharField(choices=[('queued', 'Na fila'), ('running', 'Em execução'), ('completed', 'Concluída'), ('failed', 'Falhou'), ('cancelled', 'Cancelada')], default='queued', max_length=16)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('max_attempts', models.PositiveSmallIntegerField(default=2)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_owner', models.CharField(blank=True, default='', max_length=120)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('execution_mode', models.CharField(blank=True, default='', max_length=24)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('opinion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_tasks', to='futebol.tacticalagentopinion')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='futebol.tacticalcommissionrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'ordering': ['run', 'specialty', 'attempt'],
                'indexes': [models.Index(fields=['tenant', 'status', 'available_at'], name='commission_task_queue_idx'), models.Index(fields=['run', 'status'], name='commission_task_run_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tacticalcommissiontask',
            constraint=models.UniqueConstraint(fields=('tenant', 'run', 'specialty', 'attempt'), name='uniq_tactical_commission_task_attempt'),
        ),
        migrations.AddIndex(
            model_name='tacticalcommissionrun',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='commission_run_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='tacticalcommissionrun',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uniq_tactical_commission_idempotency'),
        ),
    ]
