# Generated by Django 4.2.30 on 2026-07-12 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('futebol', '0028_tactical_commission_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacticalcommissionrun',
            name='review_decision',
            field=models.CharField(blank=True, choices=[('approved_training', 'Aprovada para treinamento'), ('rejected', 'Rejeitada')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='tacticalcommissionrun',
            name='review_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tacticalcommissionrun',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tacticalcommissionrun',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_tactical_commission_runs', to=settings.AUTH_USER_MODEL),
        ),
    ]
