# Generated by Django 4.2.30 on 2026-07-12 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('futebol', '0029_tacticalcommissionrun_review_decision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacticalBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.JSONField(blank=True, default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tactical_board', to='futebol.lineupdraft')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_tactical_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prancheta tática',
                'verbose_name_plural': 'Pranchetas táticas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TacticalBoardVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('document', models.JSONField(default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('change_note', models.TextField(blank=True, default='')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='futebol.tacticalboard')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tactical_board_versions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='futebol.tenant')),
            ],
            options={
                'verbose_name': 'Versão da prancheta tática',
                'verbose_name_plural': 'Versões da prancheta tática',
                'ordering': ['-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='tacticalboardversion',
            constraint=models.UniqueConstraint(fields=('tenant', 'board', 'version'), name='uniq_tactical_board_version'),
        ),
        migrations.AddConstraint(
            model_name='tacticalboardversion',
            constraint=models.UniqueConstraint(fields=('tenant', 'board', 'content_hash'), name='uniq_tactical_board_hash'),
        ),
    ]
