# Generated by Django 4.2.30 on 2026-07-13 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0030_tactical_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSportsDataBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset_id', models.CharField(max_length=120)),
                ('dataset_version', models.CharField(max_length=80)),
                ('content_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], max_length=16)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('manifest', models.JSONField(default=dict)),
                ('license_id', models.CharField(max_length=80)),
                ('attribution', models.CharField(max_length=240)),
                ('quality', models.CharField(max_length=40)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Versão da Base Esportiva Global',
                'verbose_name_plural': 'Versões da Base Esportiva Global',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSportsDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('football_data_org', 'football-data.org'), ('statsbomb_open', 'StatsBomb Open Data'), ('skillcorner_open', 'SkillCorner Open Data'), ('licensed_provider', 'Provider licenciado')], max_length=32)),
                ('capabilities', models.JSONField(default=list)),
                ('license_id', models.CharField(max_length=80)),
                ('license_url', models.URLField(blank=True, default='')),
                ('attribution', models.CharField(max_length=240)),
                ('quality', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=False)),
                ('operational_status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('degraded', 'Degradada'), ('disabled', 'Desabilitada'), ('research_only', 'Somente P&D'), ('contract_required', 'Contrato necessário')], default='draft', max_length=24)),
                ('adapter_version', models.CharField(blank=True, default='', max_length=32)),
                ('schema_version', models.CharField(blank=True, default='', max_length=32)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=240)),
            ],
            options={
                'verbose_name': 'Fonte da Base Esportiva Global',
                'verbose_name_plural': 'Fontes da Base Esportiva Global',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSportsSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset_id', models.CharField(max_length=120)),
                ('trigger', models.CharField(default='scheduler', max_length=32)),
                ('status', models.CharField(choices=[('processing', 'Processando'), ('completed', 'Concluída'), ('failed', 'Falhou')], default='processing', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rate_limit', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, default='', max_length=240)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_runs', to='futebol.globalsportsdatabatch')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_runs', to='futebol.globalsportsdatasource')),
            ],
            options={
                'verbose_name': 'Execução de Atualização da Plataforma',
                'verbose_name_plural': 'Execuções de Atualização da Plataforma',
                'ordering': ['-started_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSportsDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.CharField(max_length=64)),
                ('provider_record_id', models.CharField(max_length=160)),
                ('provider_updated_at', models.DateTimeField(blank=True, null=True)),
                ('observed_at', models.DateTimeField()),
                ('ingested_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('source_url', models.URLField(blank=True, default='')),
                ('content_hash', models.CharField(max_length=64)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='futebol.globalsportsdatabatch')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='futebol.globalsportsdatasource')),
            ],
            options={
                'verbose_name': 'Registro da Base Esportiva Global',
                'verbose_name_plural': 'Registros da Base Esportiva Global',
                'ordering': ['capability', 'provider_record_id'],
            },
        ),
        migrations.AddField(
            model_name='globalsportsdatabatch',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='futebol.globalsportsdatasource'),
        ),
        migrations.AddConstraint(
            model_name='globalsportsdatarecord',
            constraint=models.UniqueConstraint(fields=('batch', 'capability', 'provider_record_id'), name='uniq_global_sports_record_per_batch'),
        ),
        migrations.AddConstraint(
            model_name='globalsportsdatabatch',
            constraint=models.UniqueConstraint(fields=('source', 'dataset_id', 'content_hash'), name='uniq_global_sports_data_content'),
        ),
    ]
