# Generated by Django 4.2.30 on 2026-07-13 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0034_purge_tenant_promoted_global_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacticalcommissionrun',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_runs', to='futebol.matchdossier'),
        ),
        migrations.AddField(
            model_name='tacticalcommissiontask',
            name='specialist_opinion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_tasks', to='futebol.specialistopinion'),
        ),
        migrations.AlterField(
            model_name='matchdossier',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('processing', 'IA em processamento'), ('partial', 'IA parcialmente concluída'), ('ready', 'Pronto para revisão'), ('failed', 'Falhou')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='tacticalcommissionrun',
            name='artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_runs', to='futebol.sportsdataartifact'),
        ),
        migrations.AddConstraint(
            model_name='tacticalcommissionrun',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('artifact__isnull', False), ('dossier__isnull', True)), models.Q(('artifact__isnull', True), ('dossier__isnull', False)), _connector='OR'), name='commission_run_exactly_one_target'),
        ),
    ]
