# Generated by Django 4.2.30 on 2026-07-13 22:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futebol', '0035_tacticalcommissionrun_dossier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagent',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=3),
        ),
    ]
