# Generated by Django 4.2.30 on 2026-07-13 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('futebol', '0036_alter_aiagent_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovider',
            name='operational_data_authorization_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='operational_data_authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='operational_data_authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_operational_ai_providers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='operational_data_processing_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialistopinion',
            name='duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specialistopinion',
            name='prompt_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='specialistopinion',
            name='prompt_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='specialistopinion',
            name='provider_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='specialistopinion',
            name='provider_usage',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
